{
 "title": "Mirakurun",
 "tags": [ "mirakurun" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"mirakurun\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mirakurun Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirakurun_status_version{instance=\"$Instance\"}",
     "legendFormat": "{{mirakurun}}"
    }
   ]
  },
  {
   "title": "Node Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirakurun_status_version{instance=\"$Instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Arch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirakurun_status_process{instance=\"$Instance\"}",
     "legendFormat": "{{arch}}"
    }
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirakurun_status_process{instance=\"$Instance\"}",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "Scrape Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(mirakurun_scrape_collector_success{instance=\"$Instance\"}[$__interval]) == bool 1",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirakurun_status_memory_usage{instance=\"$Instance\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(mirakurun_status_memory_usage{instance=\"$Instance\"})",
     "legendFormat": "Memory Usage Total"
    }
   ]
  },
  {
   "title": "Free Tuners",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(mirakurun_tuners_free_tuner{instance=\"$Instance\"} * on(index) group_left(type) mirakurun_tuners_device{instance=\"$Instance\"}) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EPG Stored Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirakurun_status_epg_stored_events{instance=\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Packets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mirakurun_tuners_stream_packets{instance=\"$Instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirakurun_status_error_count{instance=\"$Instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fault Tuner",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(mirakurun_tuners_fault_tuner{instance=\"$Instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Drops",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(mirakurun_tuners_stream_drops{instance=\"$Instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tuner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Tuner Used",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(index, name, type) ((count by(index) (mirakurun_tuners_users{instance=\"$Instance\"}) * on(index) group_left(name, type) mirakurun_tuners_device{instance=\"$Instance\"}) or (mirakurun_tuners_device{instance=\"$Instance\"} * 0))",
     "legendFormat": "{{name}} 【{{type}}】"
    }
   ]
  },
  {
   "title": "Tuner Used",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "mirakurun_tuners_device{instance=\"$Instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mirakurun_tuners_users{instance=\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "mirakurun_service_service{instance=\"$Instance\", service_type=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}